### ISSUE TITLE
Erro creating instance

### ISSUE THREAD

**Issue by samako41** [davidmonterocrespo24/OdooMicroSaas#27]
Impacted versions: 16

Steps to reproduce: create a new instance

Current behavior: Traceback (most recent call last):
  File "/opt/odoo/extra_addons/micro_saas/models/odoo_docker_instance.py", line 324, in excute_command
    result = subprocess.run(cmd, shell=shell, check=check, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'docker-compose -f /opt/odoo/odoo_docker/data/icit/docker-compose.yml up -d' returned non-zero exit status 255.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/odoo/extra_addons/micro_saas/models/odoo_docker_instance.py", line 247, in start_instance
    self.excute_command(cmd, shell=True, check=True)
  File "/opt/odoo/extra_addons/micro_saas/models/odoo_docker_instance.py", line 327, in excute_command
    raise "Error to execute command: %s" % cmd
TypeError: exceptions must derive from BaseException
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1589, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1616, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/http.py", line 1820, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 466, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/extra_addons/micro_saas/models/odoo_docker_instance.py", line 255, in start_instance
    self.add_to_log("[ERROR]  " + e.stderr.decode('utf-8'))
AttributeError: 'TypeError' object has no attribute 'stderr'
The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://46.101.200.107:8069/web/assets/112-b62097b/web.assets_backend.min.js:987:163)
    at XMLHttpRequest. (http://46.101.200.107:8069/web/assets/112-b62097b/web.assets_backend.min.js:995:13)

Expected behavior: a new instance should be created

Video/Screenshot link (optional): 46.101.200.107:8069 username and password is admin

**Comment by davidmonterocrespo24** [comment]
fixed
