### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kach200** [davidmonterocrespo24/OdooMicroSaas#6]
Impacted versions: 

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo16/16.0/odoo/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo16/16.0/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo16/16.0/odoo/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo16/16.0/odoo/odoo/http.py", line 1815, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo16/16.0/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo16/16.0/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo16/16.0/odoo/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo16/16.0/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo16/16.0/odoo/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo16/16.0/odoo/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo16/16.0/odoo/odoo/models.py", line 6532, in onchange
    todo = [
  File "/opt/odoo16/16.0/odoo/odoo/models.py", line 6535, in <listcomp>
    if name not in done and snapshot0.has_changed(name)
  File "/opt/odoo16/16.0/odoo/odoo/models.py", line 6318, in has_changed
    return self[name] != record[name]
  File "/opt/odoo16/16.0/odoo/odoo/models.py", line 5891, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo16/16.0/odoo/odoo/fields.py", line 1157, in __get__
    self.recompute(record)
  File "/opt/odoo16/16.0/odoo/odoo/fields.py", line 1365, in recompute
    apply_except_missing(self.compute_value, recs)
  File "/opt/odoo16/16.0/odoo/odoo/fields.py", line 1338, in apply_except_missing
    func(records)
  File "/opt/odoo16/16.0/odoo/odoo/fields.py", line 1387, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo16/16.0/odoo/odoo/models.py", line 4215, in _compute_field_value
    fields.determine(field.compute, self)
  File "/opt/odoo16/16.0/odoo/odoo/fields.py", line 97, in determine
    return needle(*args)
  File "/opt/odoo16/16.0/extra-addons/micro_saas/models/odoo_docker_instance.py", line 30, in _compute_addons_path
    repo_path = name_repo_url = line.repository_id.name.split('/')[-1]
AttributeError: 'bool' object has no attribute 'split'

The above server error caused the following client error:
null

**Comment by davidmonterocrespo24** [comment]
The bug was fixed
#15.0
#16.0
